; ============================================================
; AXON LLVM IR — module aieonyx.aegis.monitor
; Generated by AXON Native Backend — Phase 4
; Copyright © 2026 Edison Lepiten — AIEONYX
; ============================================================

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-none-elf"

define i64 @classify(i64 %signal) {
entry:
  switch i64 0, label %match_arm_2 [
    i64 0, label %match_arm_0
    i64 1, label %match_arm_1
  ]
match_arm_0:
  ret i64 0
match_arm_1:
  ret i64 0
match_arm_2:
  ret i64 0
match_merge_0:
  ret i64 0
}

define i64 @monitor() {
entry:
  ret i64 0
}

