// ============================================================
// Generated by AXON Transpiler — Phase 3
// Copyright © 2026 Edison Lepiten — AIEONYX
// DO NOT EDIT — this file is generated from AXON source
// ============================================================

// module aieonyx.aegis.monitor

#![allow(dead_code, unused_variables, unused_imports)]

use axon_rt::defer;

use axon_std::sys::sel4::ipc as ipc;
use axon_std::mesh::collective as collective;

#[derive(Debug, Clone, PartialEq)]
pub enum ThreatLevel {
    Clear,
    Advisory {
        detail : String,
    },
    Critical {
        layer : i64,
        detail : String,
    },
}

#[derive(Debug, Clone)]
pub struct Signal {
    pub severity : i64,
    pub message : String,
    pub layer : i64,
}

pub fn classify(signal: Signal) -> ThreatLevel{
    match signal.severity {
        0 => { return ThreatLevel::Clear; },
        1 => { return ThreatLevel::Advisory{ detail: signal.message }; },
        _ => { return ThreatLevel::Critical{ layer: signal.layer, detail: signal.message }; },
    }
}

pub async fn monitor() -> Result<(), Box<dyn std::error::Error>> /* uses [ipc.read, collective.emit] */{
    let channel = ipc::open_channel()?; // let@ ephemeral
    // defer channel.close(): called at scope exit
    for signal in channel.signals {
        let level = classify(signal);
        collective::emit(level);
    }
    Ok(())
}

