// Generated by AXON Transpiler — axon run
// To add program logic, edit monitor.axon
use monitor_axon_out::*;

fn main() {
println!("AXON program 'monitor' loaded.");
println!("Implement main() logic in monitor.axon");
}
