# Copyright (c) 2026 Edison Lepiten / AIEONYX
# SPDX-License-Identifier: Apache-2.0

[package]
name = "axonc"
version = "0.55.0"
edition = "2021"
authors = ["Edison Lepiten <aieonyx.eu@gmail.com>"]
description = "axonc — AXONYX sovereign compiler driver. Bootstrap checkpoint. P55."
license = "Apache-2.0"

[dependencies]
axon_std_string = { path = "../axon_std/string" }
axon_native     = { path = "../axon_native" }

[dev-dependencies]
