// Copyright (c) 2026 Edison Lepiten / AIEONYX
// SPDX-License-Identifier: Apache-2.0
//
// Type constraint definitions for AXONYX inference.
// Constraints are generated by infer.rs and resolved by unify.rs.
// At P52: eager constraint resolution (generate + unify immediately).

use crate::ty::{Ty, TyVar};

/// A type constraint produced during inference.
#[derive(Debug, Clone, PartialEq)]
pub enum Constraint {
    /// T1 must equal T2
    Eq(Ty, Ty),
    /// Type variable V must equal T
    VarEq(TyVar, Ty),
}
