#![allow(dead_code)]
// axon_cli::fcig — Foreign Code Immunity Gate. SPEC: 6B-01
// Bio: Restriction Enzymes — self vs non-self at the molecular level.
// Own DNA is methylated (OIH-marked). Foreign DNA is cut (rejected).

#[derive(Debug,Clone,PartialEq,Eq)]
pub enum LinkProfile{SeL4Strict,DevMode}

impl std::fmt::Display for LinkProfile{
    fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{
        match self{
            LinkProfile::SeL4Strict=>write!(f,"seL4-strict"),
            LinkProfile::DevMode=>write!(f,"dev-mode"),
        }
    }
}

#[derive(Debug,Clone,PartialEq,Eq)]
pub enum OIHStatus{
    Valid{key:String},
    Missing,
    Tampered,
    Wrapped,
}

#[derive(Debug,Clone)]
pub struct ObjectReport{
    pub name:String,
    pub oih_status:OIHStatus,
}

impl ObjectReport{
    pub fn is_trusted(&self)->bool{
        matches!(&self.oih_status,OIHStatus::Valid{..}|OIHStatus::Wrapped)
    }
}

#[derive(Debug,Clone)]
pub enum FCIGError{
    ForeignObject{name:String},
    TamperedObject{name:String},
}

impl std::fmt::Display for FCIGError{
    fn fmt(&self,f:&mut std::fmt::Formatter<'_>)->std::fmt::Result{
        match self{
            FCIGError::ForeignObject{name}=>write!(f,"Foreign object {} rejected: no OIH. Wrap with: axon wrap {} --trust developer",name,name),
            FCIGError::TamperedObject{name}=>write!(f,"Tampered object {} rejected: OIH signature invalid",name),
        }
    }
}
#[derive(Debug)]
pub struct FCIGReport{
    pub profile:LinkProfile,
    pub objects:Vec<ObjectReport>,
    pub errors:Vec<FCIGError>,
    pub warnings:Vec<String>,
}

impl FCIGReport{
    pub fn all_trusted(&self)->bool{self.errors.is_empty()}
    pub fn format(&self)->String{
        let mut out=String::new();
        out.push_str("
AXON FOREIGN CODE IMMUNITY GATE
");
        for obj in &self.objects{
            let status=match &obj.oih_status{
                OIHStatus::Valid{key}=>format!("OIH: VALID (axon-compiler-1.0, key: {})",key),
                OIHStatus::Missing=>"OIH: MISSING".to_string(),
                OIHStatus::Tampered=>"OIH: TAMPERED".to_string(),
                OIHStatus::Wrapped=>"OIH: WRAPPED (.aix trust envelope)".to_string(),
            };
            out.push_str(&format!("  {:<30} {}
",obj.name,status));
        }
        out.push_str(&format!("
  [{}]
",self.profile));
        for e in &self.errors{
            out.push_str(&format!("  ERROR: {}
",e));
        }
        for w in &self.warnings{
            out.push_str(&format!("  WARNING: {}
",w));
        }
        if self.all_trusted(){
            out.push_str("  All objects verified. Link authorized.
");
        }
        out
    }
}

pub struct OIHValidator;

impl OIHValidator{
    /// Check a source/object file for OIH markers.
    /// Phase 6: source-level detection. PHASE7: ELF section .axon_oih parsing.
    pub fn check(name:&str,content:&str)->ObjectReport{
        // Phase 6: detect OIH markers in source content
        // PHASE7: read .axon_oih ELF section and verify signature
        if content.contains(".aix-trust-envelope"){
            return ObjectReport{name:name.to_string(),oih_status:OIHStatus::Wrapped};
        }
        if content.contains("@oih-tampered"){
            return ObjectReport{name:name.to_string(),oih_status:OIHStatus::Tampered};
        }
        if content.contains("Generated by AXON Transpiler")||
           content.contains("@oih:"){
            let key=Self::extract_key(content);
            return ObjectReport{name:name.to_string(),oih_status:OIHStatus::Valid{key}};
        }
        ObjectReport{name:name.to_string(),oih_status:OIHStatus::Missing}
    }

    fn extract_key(content:&str)->String{
        for line in content.lines(){
            if let Some(rest)=line.trim().strip_prefix("@oih:"){
                return rest.trim().to_string();
            }
        }
        "0xAB12".to_string() // default compiler key stub
    }

    /// Run FCIG on a set of object files.
    /// SPEC: 6B-01
    pub fn run(objects:Vec<(String,String)>,profile:LinkProfile)->FCIGReport{
        let mut reports=Vec::new();
        let mut errors=Vec::new();
        let mut warnings=Vec::new();
        for (name,content) in &objects{
            let report=Self::check(name,content);
            match &report.oih_status{
                OIHStatus::Missing=>{
                    match profile{
                        LinkProfile::SeL4Strict=>{
                            errors.push(FCIGError::ForeignObject{name:name.clone()});
                        }
                        LinkProfile::DevMode=>{
                            warnings.push(format!("Foreign object {} linked without OIH. Logged to audit trail.",name));
                        }
                    }
                }
                OIHStatus::Tampered=>{
                    errors.push(FCIGError::TamperedObject{name:name.clone()});
                }
                _=>{}
            }
            reports.push(report);
        }
        FCIGReport{profile,objects:reports,errors,warnings}
    }
}
#[cfg(test)]
mod tests{
    use super::*;

    fn axon_src()->(&'static str,&'static str){
        ("monitor.rs","// Generated by AXON Transpiler
pub fn main(){}")
    }
    fn foreign_src()->(&'static str,&'static str){
        ("libext.a","extern_fn main(){return 0;}")
    }
    fn wrapped_src()->(&'static str,&'static str){
        ("wrapped.aix",".aix-trust-envelope
fn main(){}")
    }

    #[test]
    fn test_axon_source_valid_oih(){
        let (n,c)=axon_src();
        let r=OIHValidator::check(n,c);
        assert!(r.is_trusted());
        assert!(matches!(r.oih_status,OIHStatus::Valid{..}));
    }

    #[test]
    fn test_foreign_missing_oih(){
        let (n,c)=foreign_src();
        let r=OIHValidator::check(n,c);
        assert!(!r.is_trusted());
        assert_eq!(r.oih_status,OIHStatus::Missing);
    }

    #[test]
    fn test_wrapped_is_trusted(){
        let (n,c)=wrapped_src();
        let r=OIHValidator::check(n,c);
        assert!(r.is_trusted());
        assert_eq!(r.oih_status,OIHStatus::Wrapped);
    }

    #[test]
    fn test_tampered_detected(){
        let r=OIHValidator::check("bad.o","@oih-tampered
fn f(){}");
        assert!(!r.is_trusted());
        assert_eq!(r.oih_status,OIHStatus::Tampered);
    }

    #[test]
    fn test_sel4_strict_rejects_foreign(){
        let (n,c)=foreign_src();
        let report=OIHValidator::run(vec![(n.to_string(),c.to_string())],LinkProfile::SeL4Strict);
        assert!(!report.all_trusted());
        assert_eq!(report.errors.len(),1);
        assert!(report.warnings.is_empty());
    }

    #[test]
    fn test_devmode_warns_foreign(){
        let (n,c)=foreign_src();
        let report=OIHValidator::run(vec![(n.to_string(),c.to_string())],LinkProfile::DevMode);
        assert!(report.all_trusted());
        assert_eq!(report.warnings.len(),1);
        assert!(report.errors.is_empty());
    }

    #[test]
    fn test_mixed_objects(){
        let (an,ac)=axon_src();
        let (fn_,fc)=foreign_src();
        let report=OIHValidator::run(vec![
            (an.to_string(),ac.to_string()),(fn_.to_string(),fc.to_string())
        ],LinkProfile::SeL4Strict);
        assert!(!report.all_trusted());
        assert_eq!(report.objects.len(),2);
    }

    #[test]
    fn test_report_format_contains_gate_header(){
        let (n,c)=axon_src();
        let report=OIHValidator::run(vec![(n.to_string(),c.to_string())],LinkProfile::DevMode);
        let txt=report.format();
        assert!(txt.contains("FOREIGN CODE IMMUNITY GATE"));
        assert!(txt.contains("OIH: VALID"));
    }

    #[test]
    fn test_all_trusted_clean_run(){
        let (an,ac)=axon_src();
        let (wn,wc)=wrapped_src();
        let report=OIHValidator::run(vec![
            (an.to_string(),ac.to_string()),(wn.to_string(),wc.to_string())
        ],LinkProfile::SeL4Strict);
        assert!(report.all_trusted());
    }
}
