; ============================================================
; AXON LLVM IR — module aieonyx.gpu.vector_add
; Generated by AXON Native Backend — Phase 4
; Copyright © 2026 Edison Lepiten — AIEONYX
; ============================================================

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define double @add(double %a, double %b) {
entry:
  %add_0 = fadd double %a, %b
  ret double %add_0
}

define i64 @vector_add(i64 %x, i64 %y) {
entry:
  %add_1 = add i64 %x, %y
  ret i64 %add_1
}

