# Copyright (c) 2026 Edison Lepiten / AIEONYX
# SPDX-License-Identifier: Apache-2.0

[package]
name = "axon_codegen"
version = "0.53.0"
edition = "2021"
authors = ["Edison Lepiten <aieonyx.eu@gmail.com>"]
description = "axon_codegen — LLVM IR emission. AXON emits its own IR. P53."
license = "Apache-2.0"

[dependencies]
axon_std_string = { path = "../axon_std/string" }
axon_parse      = { path = "../axon_parse" }
axon_hir        = { path = "../axon_hir" }
axon_infer      = { path = "../axon_infer" }

[dev-dependencies]
