// Copyright (c) 2026 Edison Lepiten / AIEONYX
// axon_aarch64 P71 — AArch64 GNU assembly emitter
//
// Emits GNU-syntax AArch64 assembly (.s) from AxIr.
// Assembled with: aarch64-linux-gnu-as -o output.o output.s
//
// Variable allocation: simple stack frame, each variable gets 8 bytes.
// Maximum 16 variables (matches axon_interp::MAX_VARS).
// String literals go in .rodata section.

use crate::ir::{AxIr, BinOpKind, Aarch64Target, PrintImpl};
use std::collections::HashMap;

pub const MAX_VARS: usize = 16;
pub const VAR_SLOT_SIZE: usize = 8;
pub const FRAME_SIZE: usize = MAX_VARS * VAR_SLOT_SIZE + 16; // +16 for x29/x30

/// Emits complete AArch64 .s file from AxIr sequence.
pub fn emit_asm(ir: &[AxIr], target: &Aarch64Target) -> String {
    let mut out = String::new();
    let mut emitter = AsmEmitter::new(target);
    emitter.emit_file_header(&mut out);
    emitter.emit_rodata(ir, &mut out);
    emitter.emit_text(ir, &mut out);
    out
}

struct AsmEmitter<'a> {
    target: &'a Aarch64Target,
    var_slots: HashMap<String, usize>, // var name → stack offset from fp
    next_slot: usize,
    string_literals: Vec<(String, String)>, // (label, text)
    str_counter: usize,
}

impl<'a> AsmEmitter<'a> {
    fn new(target: &'a Aarch64Target) -> Self {
        Self {
            target,
            var_slots: HashMap::new(),
            next_slot: 0,
            string_literals: Vec::new(),
            str_counter: 0,
        }
    }

    fn var_offset(&mut self, name: &str) -> usize {
        if let Some(&off) = self.var_slots.get(name) {
            return off;
        }
        let off = self.next_slot * VAR_SLOT_SIZE;
        self.var_slots.insert(name.to_string(), off);
        self.next_slot += 1;
        off
    }

    fn new_str_label(&mut self, text: &str) -> String {
        let label = format!(".Lstr_{}", self.str_counter);
        self.str_counter += 1;
        self.string_literals.push((label.clone(), text.to_string()));
        label
    }

    fn emit_file_header(&self, out: &mut String) {
        out.push_str("// Copyright (c) 2026 Edison Lepiten / AIEONYX\n");
        out.push_str("// Generated by axon_aarch64 P71 — sovereign AArch64 codegen\n");
        out.push_str(&format!("// Target: {}\n", self.target.triple()));
        out.push('\n');
        out.push_str(".arch armv8-a\n");
        if self.target.is_freestanding() {
            out.push_str(".section .text\n");
        }
        out.push('\n');
    }

    fn emit_rodata(&mut self, ir: &[AxIr], out: &mut String) {
        // Pre-scan for string literals
        let mut strs = Vec::new();
        for node in ir {
            if let AxIr::PrintStr { text } = node {
                strs.push(text.clone());
            }
        }
        if strs.is_empty() { return; }

        out.push_str(".section .rodata\n");
        for text in strs {
            let label = format!(".Lstr_{}", self.str_counter);
            self.str_counter += 1;
            out.push_str(&format!("{}:\n", label));
            out.push_str(&format!("  .ascii \"{}\\n\"\n", text.replace('"', "\\\"")));
            out.push_str(&format!(".Lstr_{}_len = . - {}\n", self.str_counter - 1, label));
            self.string_literals.push((label, text));
        }
        out.push('\n');
    }

    fn emit_text(&mut self, ir: &[AxIr], out: &mut String) {
        out.push_str(".section .text\n");
        if self.target.is_freestanding() {
            self.emit_freestanding_start(out);
        }
        out.push_str(".global axon_main\n");
        out.push_str("axon_main:\n");
        // Function prologue
        out.push_str(&format!("  stp x29, x30, [sp, #-{}]!\n", FRAME_SIZE));
        out.push_str("  mov x29, sp\n");
        out.push('\n');

        let mut str_idx = 0usize;
        for node in ir {
            match node {
                AxIr::ProgramStart | AxIr::ProgramEnd => {}
                AxIr::FnEntry { name } => {
                    out.push_str(&format!("{}:\n", name));
                }
                AxIr::FnExit => {
                    out.push_str("  ret\n");
                }
                AxIr::LoadImm { var, value } => {
                    let off = self.var_offset(var);
                    out.push_str(&format!("  // let {} = {}\n", var, value));
                    self.emit_load_imm(out, *value);
                    out.push_str(&format!("  str x0, [x29, #{}]\n", off + FRAME_SIZE));
                }
                AxIr::LoadVar { dst, src } => {
                    let src_off = self.var_offset(src);
                    let dst_off = self.var_offset(dst);
                    out.push_str(&format!("  // let {} = {}\n", dst, src));
                    out.push_str(&format!("  ldr x0, [x29, #{}]\n", src_off + FRAME_SIZE));
                    out.push_str(&format!("  str x0, [x29, #{}]\n", dst_off + FRAME_SIZE));
                }
                AxIr::BinOp { dst, lhs, op, rhs } => {
                    let lhs_off = self.var_offset(lhs);
                    let rhs_off = self.var_offset(rhs);
                    let dst_off = self.var_offset(dst);
                    out.push_str(&format!("  // let {} = {} {} {}\n",
                        dst, lhs, op.as_str(), rhs));
                    out.push_str(&format!("  ldr x0, [x29, #{}]\n", lhs_off + FRAME_SIZE));
                    // Try rhs as immediate first
                    if let Ok(rhs_str) = std::str::from_utf8(rhs.as_bytes()) {
                        if let Ok(n) = rhs_str.parse::<i64>() {
                            match op {
                                BinOpKind::Add => out.push_str(&format!("  add x0, x0, #{}\n", n)),
                                BinOpKind::Sub => out.push_str(&format!("  sub x0, x0, #{}\n", n)),
                                BinOpKind::Mul => {
                                    self.emit_load_imm(out, n);
                                    out.push_str("  mul x2, x1, x0\n");
                                    out.push_str("  mov x0, x2\n");
                                }
                            }
                        } else {
                            out.push_str(&format!("  ldr x1, [x29, #{}]\n", rhs_off + FRAME_SIZE));
                            match op {
                                BinOpKind::Add => out.push_str("  add x0, x0, x1\n"),
                                BinOpKind::Sub => out.push_str("  sub x0, x0, x1\n"),
                                BinOpKind::Mul => out.push_str("  mul x0, x0, x1\n"),
                            }
                        }
                    }
                    out.push_str(&format!("  str x0, [x29, #{}]\n", dst_off + FRAME_SIZE));
                }
                AxIr::PrintStr { .. } => {
                    let label = format!(".Lstr_{}", str_idx);
                    let len_label = format!(".Lstr_{}_len", str_idx);
                    str_idx += 1;
                    out.push_str(&format!("  // print string\n"));
                    match self.target.print_impl() {
                        PrintImpl::Syscall => {
                            // Linux: write(1, str, len)
                            out.push_str("  mov x0, #1\n"); // stdout
                            out.push_str(&format!("  adrp x1, {}\n", label));
                            out.push_str(&format!("  add x1, x1, :lo12:{}\n", label));
                            out.push_str(&format!("  mov x2, #{}\n", 32)); // approx len
                            out.push_str("  mov x8, #64\n"); // write syscall
                            out.push_str("  svc #0\n");
                        }
                        PrintImpl::Uart => {
                            // aiXos: write to UART MMIO (0x09000000 PL011)
                            out.push_str("  adrp x1, {}\n");
                            out.push_str(&format!("  add x1, x1, :lo12:{}\n", label));
                            out.push_str("  mov x2, #32\n"); // approx len
                            out.push_str("  mov x0, #0x09000000\n"); // UART base
                            out.push_str("  bl axon_uart_write\n");
                        }
                    }
                }
                AxIr::PrintVar { var } => {
                    let off = self.var_offset(var);
                    out.push_str(&format!("  // print {}\n", var));
                    out.push_str(&format!("  ldr x0, [x29, #{}]\n", off + FRAME_SIZE));
                    out.push_str("  bl axon_print_i64\n");
                }
                AxIr::AwpSend { payload } => {
                    out.push_str(&format!("  // awp send: {} (stub)\n", payload));
                    // Stub: no-op in freestanding v0
                }
            }
        }

        // Function epilogue
        out.push('\n');
        out.push_str(&format!("  ldp x29, x30, [sp], #{}\n", FRAME_SIZE));
        if self.target.is_freestanding() {
            out.push_str("  b .\n"); // infinite loop (bare-metal exit)
        } else {
            // Linux: exit(0)
            out.push_str("  mov x0, #0\n");
            out.push_str("  mov x8, #93\n"); // exit syscall
            out.push_str("  svc #0\n");
        }
        out.push('\n');

        // Runtime helpers
        self.emit_print_i64_helper(out);
    }

    fn emit_freestanding_start(&self, out: &mut String) {
        out.push_str("// Freestanding entry point — no OS, no CRT\n");
        out.push_str(".global _start\n");
        out.push_str("_start:\n");
        // Stack pointer set by linker script (__stack_top symbol)
        out.push_str("  adrp x0, __stack_top\n");
        out.push_str("  add sp, x0, :lo12:__stack_top\n");
        // Zero BSS section
        out.push_str("  adrp x0, __bss_start\n");
        out.push_str("  add x0, x0, :lo12:__bss_start\n");
        out.push_str("  adrp x1, __bss_end\n");
        out.push_str("  add x1, x1, :lo12:__bss_end\n");
        out.push_str(".Lbss_zero:\n");
        out.push_str("  cmp x0, x1\n");
        out.push_str("  b.ge .Lbss_zero_done\n");
        out.push_str("  str xzr, [x0], #8\n");
        out.push_str("  b .Lbss_zero\n");
        out.push_str(".Lbss_zero_done:\n");
        // Call axon_main
        out.push_str("  bl axon_main\n");
        // Halt (WFI loop)
        out.push_str(".Lhalt:\n");
        out.push_str("  wfi\n");
        out.push_str("  b .Lhalt\n");
        out.push('\n');
    }

    fn emit_load_imm(&self, out: &mut String, value: i64) {
        if value >= 0 && value <= 65535 {
            out.push_str(&format!("  mov x0, #{}\n", value));
        } else if value < 0 && value >= -65536 {
            out.push_str(&format!("  mov x0, #{}\n", value));
        } else {
            // Large immediate: use movz + movk
            let lo = (value as u64) & 0xFFFF;
            let hi = ((value as u64) >> 16) & 0xFFFF;
            out.push_str(&format!("  movz x0, #{}\n", lo));
            if hi != 0 {
                out.push_str(&format!("  movk x0, #{}, lsl #16\n", hi));
            }
        }
    }

    fn emit_print_i64_helper(&self, out: &mut String) {
        // axon_print_i64: print x0 as decimal + newline
        // Uses Linux write syscall on LinuxAarch64, UART on Freestanding
        out.push_str("// axon_print_i64: print x0 as decimal\n");
        out.push_str("axon_print_i64:\n");
        out.push_str("  stp x29, x30, [sp, #-64]!\n");
        out.push_str("  mov x29, sp\n");
        // Handle negative
        out.push_str("  cmp x0, #0\n");
        out.push_str("  b.ge .Lpos\n");
        // Print '-'
        out.push_str("  mov x1, #45\n"); // '-'
        out.push_str("  strb w1, [sp, #32]\n");
        out.push_str("  neg x0, x0\n");
        out.push_str(".Lpos:\n");
        // Digit extraction loop
        out.push_str("  mov x1, #10\n");
        out.push_str("  add x2, sp, #48\n"); // digit buffer end
        out.push_str("  mov x3, #0\n");    // digit count
        out.push_str(".Ldigit_loop:\n");
        out.push_str("  udiv x4, x0, x1\n");
        out.push_str("  msub x5, x4, x1, x0\n");
        out.push_str("  add x5, x5, #48\n"); // to ASCII
        out.push_str("  strb w5, [x2, x3]\n");
        out.push_str("  add x3, x3, #1\n");
        out.push_str("  mov x0, x4\n");
        out.push_str("  cbnz x0, .Ldigit_loop\n");
        // Add newline
        out.push_str("  mov x5, #10\n");
        out.push_str("  strb w5, [x2, x3]\n");
        out.push_str("  add x3, x3, #1\n");
        // Write (digits are reversed — emit from end)
        match self.target.print_impl() {
            PrintImpl::Syscall => {
                out.push_str("  mov x0, #1\n");
                out.push_str("  mov x1, x2\n");
                out.push_str("  mov x2, x3\n");
                out.push_str("  mov x8, #64\n");
                out.push_str("  svc #0\n");
            }
            PrintImpl::Uart => {
                out.push_str("  mov x0, #0x09000000\n");
                out.push_str("  bl axon_uart_write\n");
            }
        }
        out.push_str("  ldp x29, x30, [sp], #64\n");
        out.push_str("  ret\n\n");
    }
}
