# Copyright (c) 2026 Edison Lepiten / AIEONYX
# SPDX-License-Identifier: Apache-2.0

[package]
name = "axon_parse"
version = "0.50.0"
edition = "2021"
authors = ["Edison Lepiten <aieonyx.eu@gmail.com>"]
description = "axon_parse — Recursive descent parser. AXON grammar in .ax source. P50."
license = "Apache-2.0"

[dependencies]
axon_std_string = { path = "../axon_std/string" }
axon_lex = { path = "../axon_lex" }

[dev-dependencies]
tempfile = "3"
