// ============================================================
// AXON Codegen — generator.rs
// Main transpiler — walks AST, emits Rust source
// Copyright © 2026 Edison Lepiten — AIEONYX
// github.com/aieonyx/axon
//
// Phase 3 implementation milestones:
//   P3-01 (now):  scaffold, struct, enum → Rust
//   P3-02:        fn, task → Rust fn / async fn
//   P3-03:        statements → Rust statements
//   P3-04:        expressions → Rust expressions
//   P3-05:        memory model → Rust ownership
//   P3-06:        defer/with → Rust drop guards
//   P3-07:        module/import → Rust mod/use
//   P3-08:        full Aegis Monitor compiles to binary
// ============================================================

use axon_parser::ast::{
    Program, TopLevelItem,
    StructDecl, EnumDecl, VariantDecl,
    FieldDecl,
    FnDecl, TaskDecl, Param,
    Block, Stmt,
    LetStmt, MutStmt, EphemeralStmt,
    ReturnStmt, IfStmt, ForStmt, WhileStmt,
    MatchStmt, MatchArm, DeferStmt,
    AssignStmt, ExprStmt,
    Expr, Literal,
    Pattern, EnumPattern, PatternField,
    Type, MemMode,
};
use crate::types::rust_type;

// ── CodeGen struct ────────────────────────────────────────────

pub struct CodeGen {
    output : String,
    indent : usize,
}

impl CodeGen {
    pub fn new() -> Self {
        CodeGen { output: String::new(), indent: 0 }
    }

    pub fn finish(self) -> String { self.output }

    // ── Output helpers ────────────────────────────────────────

    fn line(&mut self, s: &str) {
        let indent = "    ".repeat(self.indent);
        self.output.push_str(&indent);
        self.output.push_str(s);
        self.output.push('\n');
    }

    fn blank(&mut self) { self.output.push('\n'); }

    fn indent(&mut self)   { self.indent += 1; }
    fn dedent(&mut self)   { if self.indent > 0 { self.indent -= 1; } }

    fn raw(&mut self, s: &str) { self.output.push_str(s); }

    // ── Program ───────────────────────────────────────────────

    pub fn emit_program(&mut self, program: &Program) {
        // File header
        self.line("// ============================================================");
        self.line("// Generated by AXON Transpiler — Phase 3");
        self.line("// Copyright © 2026 Edison Lepiten — AIEONYX");
        self.line("// DO NOT EDIT — this file is generated from AXON source");
        self.line("// ============================================================");
        self.blank();

        // Module path as comment
        if let Some(m) = &program.module {
            let path = m.path.iter().map(|i| i.name.as_str()).collect::<Vec<_>>().join(".");
            self.line(&format!("// module {}", path));
            self.blank();
        }

        // Suppress dead code warnings in generated code
        self.line("#![allow(dead_code, unused_variables, unused_imports)]");
        self.blank();

        // Imports → use statements (P3-07 will expand this)
        for imp in &program.imports {
            let path = imp.path.iter().map(|i| i.name.as_str()).collect::<Vec<_>>().join("::");
            if let Some(alias) = &imp.alias {
                self.line(&format!("use {} as {};", path, alias.name));
            } else {
                self.line(&format!("use {};", path));
            }
        }
        if !program.imports.is_empty() { self.blank(); }

        // Top-level items
        for item in &program.items {
            self.emit_top_level_item(item);
            self.blank();
        }
    }

    fn emit_top_level_item(&mut self, item: &TopLevelItem) {
        match item {
            TopLevelItem::Struct(s) => self.emit_struct(s),
            TopLevelItem::Enum(e)   => self.emit_enum(e),
            TopLevelItem::Fn(f)     => self.emit_fn(f),
            TopLevelItem::Task(t)   => self.emit_task(t),
            _ => self.line("// [unsupported top-level item]"),
        }
    }

    // ── Struct → Rust struct ──────────────────────────────────

    fn emit_struct(&mut self, s: &StructDecl) {
        self.line("#[derive(Debug, Clone)]");
        self.line(&format!("pub struct {} {{", s.name.name));
        self.indent();
        for field in &s.fields {
            let ty = rust_type(&field.ty);
            self.line(&format!("pub {} : {},", field.name.name, ty));
        }
        self.dedent();
        self.line("}");
    }

    // ── Enum → Rust enum ──────────────────────────────────────

    fn emit_enum(&mut self, e: &EnumDecl) {
        self.line("#[derive(Debug, Clone, PartialEq)]");
        self.line(&format!("pub enum {} {{", e.name.name));
        self.indent();
        for variant in &e.variants {
            self.emit_variant(variant);
        }
        self.dedent();
        self.line("}");
    }

    fn emit_variant(&mut self, v: &VariantDecl) {
        if v.fields.is_empty() {
            self.line(&format!("{},", v.name.name));
        } else {
            // Named struct variant — fields are FieldDecl
            self.line(&format!("{} {{", v.name.name));
            self.indent();
            for f in &v.fields {
                let ty = rust_type(&f.ty);
                self.line(&format!("{} : {},", f.name.name, ty));
            }
            self.dedent();
            self.line("},");
        }
    }

    // ── Fn → Rust fn ─────────────────────────────────────────

    fn emit_fn(&mut self, f: &FnDecl) {
        // Decorators as comments
        for d in &f.decorators {
            let name = d.name.iter().map(|i| i.name.as_str()).collect::<Vec<_>>().join(".");
            let arg  = d.args.first()
                .map(|a| format!(" \"{}\"", self.emit_expr_str(&a.value)))
                .unwrap_or_default();
            self.line(&format!("// @{}{}", name, arg));
        }

        // Signature
        let params   = self.emit_params(&f.params);
        let ret      = f.ret_type.as_ref()
            .map(|t| format!(" -> {}", rust_type(t)))
            .unwrap_or_default();
        let uses_str = f.uses.as_ref()
            .map(|u| {
                let effects = u.effects.iter()
                    .map(|e| e.parts.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join("."))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(" /* uses [{}] */", effects)
            })
            .unwrap_or_default();

        self.line(&format!("pub fn {}({}){}{}{{", f.name.name, params, ret, uses_str));
        self.indent();
        self.emit_block(&f.body);
        self.dedent();
        self.line("}");
    }

    // ── Task → Rust async fn ─────────────────────────────────

    fn emit_task(&mut self, t: &TaskDecl) {
        for d in &t.decorators {
            let name = d.name.iter().map(|i| i.name.as_str()).collect::<Vec<_>>().join(".");
            self.line(&format!("// @{}", name));
        }

        let params   = self.emit_params(&t.params);
        let ret      = t.ret_type.as_ref()
            .map(|ty| format!(" -> {}", rust_type(ty)))
            .unwrap_or_default();
        let uses_str = t.uses.as_ref()
            .map(|u| {
                let effects = u.effects.iter()
                    .map(|e| e.parts.iter().map(|p| p.name.as_str()).collect::<Vec<_>>().join("."))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!(" /* uses [{}] */", effects)
            })
            .unwrap_or_default();

        self.line(&format!("pub async fn {}({}){}{}{{", t.name.name, params, ret, uses_str));
        self.indent();
        self.emit_block(&t.body);
        self.dedent();
        self.line("}");
    }

    fn emit_params(&self, params: &[Param]) -> String {
        params.iter().map(|p| {
            let ty   = rust_type(&p.ty);
            let mode = match &p.mem_mode {
                Some(MemMode::Borrow)    => format!("&{}",     ty),
                Some(MemMode::MutBorrow) => format!("&mut {}", ty),
                Some(MemMode::Share)     => format!("std::sync::Arc<std::sync::Mutex<{}>>", ty),
                Some(MemMode::Own) | None => ty,
            };
            format!("{}: {}", p.name.name, mode)
        }).collect::<Vec<_>>().join(", ")
    }

    // ── Block → Rust block body ───────────────────────────────

    fn emit_block(&mut self, block: &Block) {
        for stmt in &block.stmts {
            self.emit_stmt(stmt);
        }
    }

    // ── Statements ────────────────────────────────────────────

    fn emit_stmt(&mut self, stmt: &Stmt) {
        match stmt {
            Stmt::Pass(_) => {
                self.line("// pass");
            }
            Stmt::Let(s)  => self.emit_let(s, false),
            Stmt::Mut(s)  => {
                let ty  = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                let val = self.emit_expr_str(&s.init);
                self.line(&format!("let mut {}{} = {};", s.name.name, ty, val));
            }
            Stmt::Ephemeral(s) => {
                // let@ → let (Rust doesn't have linear types, but we mark it)
                let ty  = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
                let val = self.emit_expr_str(&s.init);
                self.line(&format!("let {}{} = {}; // let@ ephemeral", s.name.name, ty, val));
            }
            Stmt::Return(s) => {
                if let Some(val) = &s.value {
                    let v = self.emit_expr_str(val);
                    self.line(&format!("return {};", v));
                } else {
                    self.line("return;");
                }
            }
            Stmt::If(s) => self.emit_if(s),
            Stmt::For(s) => self.emit_for(s),
            Stmt::While(s) => {
                let cond = self.emit_expr_str(&s.condition);
                self.line(&format!("while {} {{", cond));
                self.indent();
                self.emit_block(&s.body);
                self.dedent();
                self.line("}");
            }
            Stmt::Match(s) => self.emit_match(s),
            Stmt::Defer(s) => {
                // defer cleanup() →  scopeguard or manual drop
                // For now emit as a comment — P3-06 implements proper drop guards
                let expr = self.emit_expr_str(&s.expr);
                self.line(&format!("// defer: {} (P3-06 implements drop guard)", expr));
                self.line(&format!("let _defer_guard = axon_rt::defer(|| {});", expr));
            }
            Stmt::Assign(s) => {
                let val = self.emit_expr_str(&s.value);
                let target = match &s.target {
                    axon_parser::ast::AssignTarget::Ident(id) => id.name.clone(),
                    _ => "/* complex target */".into(),
                };
                self.line(&format!("{} = {};", target, val));
            }
            Stmt::Expr(s) => {
                let e = self.emit_expr_str(&s.expr);
                self.line(&format!("{};", e));
            }
            Stmt::With(s) => {
                // with expr as name: body
                // → let name = expr; { body }
                let expr = self.emit_expr_str(&s.expr);
                self.line(&format!("let {} = {}; // with scope", s.binding.name, expr));
                self.line("{");
                self.indent();
                self.emit_block(&s.body);
                self.dedent();
                self.line("}");
            }
            Stmt::Break(_)    => self.line("break;"),
            Stmt::Continue(_) => self.line("continue;"),
            _                 => self.line("// [unsupported statement]"),
        }
    }

    fn emit_let(&mut self, s: &LetStmt, _mutable: bool) {
        let ty  = s.ty.as_ref().map(|t| format!(": {}", rust_type(t))).unwrap_or_default();
        let val = self.emit_expr_str(&s.init);
        self.line(&format!("let {}{} = {};", s.name.name, ty, val));
    }

    fn emit_if(&mut self, s: &IfStmt) {
        let cond = self.emit_expr_str(&s.condition);
        self.line(&format!("if {} {{", cond));
        self.indent();
        self.emit_block(&s.then_block);
        self.dedent();

        // else-ifs
        for (cond, block) in &s.else_ifs {
            let c = self.emit_expr_str(cond);
            self.line(&format!("}} else if {} {{", c));
            self.indent();
            self.emit_block(block);
            self.dedent();
        }

        // else
        if let Some(else_block) = &s.else_block {
            self.line("} else {");
            self.indent();
            self.emit_block(else_block);
            self.dedent();
        }
        self.line("}");
    }

    fn emit_for(&mut self, s: &ForStmt) {
        let iter = self.emit_expr_str(&s.iterable);
        self.line(&format!("for {} in {} {{", s.binding.name, iter));
        self.indent();
        self.emit_block(&s.body);
        self.dedent();
        self.line("}");
    }

    fn emit_match(&mut self, s: &MatchStmt) {
        let subject = self.emit_expr_str(&s.subject);
        self.line(&format!("match {} {{", subject));
        self.indent();
        for arm in &s.arms {
            self.emit_match_arm(arm);
        }
        self.dedent();
        self.line("}");
    }

    fn emit_match_arm(&mut self, arm: &MatchArm) {
        let pat   = self.emit_pattern_str(&arm.pattern);
        let guard = arm.guard.as_ref()
            .map(|g| format!(" if {}", self.emit_expr_str(g)))
            .unwrap_or_default();
        let body  = self.emit_expr_str(&arm.body);

        // Return expressions need special arm syntax
        if body.starts_with("return") {
            // `return expr` in a match arm — emit as a block
            self.line(&format!("{}{} => {{ {}; }},", pat, guard, body));
        } else {
            self.line(&format!("{}{} => {},", pat, guard, body));
        }
    }

    // ── Pattern → Rust pattern string ────────────────────────

    fn emit_pattern_str(&self, pat: &Pattern) -> String {
        match pat {
            Pattern::Wildcard(_)  => "_".into(),
            Pattern::Binding(id)  => id.name.clone(),
            Pattern::Literal(lit) => self.emit_literal_str(lit),
            Pattern::Enum(e)      => self.emit_enum_pattern_str(e),
            Pattern::Or(pats, _)  => {
                pats.iter()
                    .map(|p| self.emit_pattern_str(p))
                    .collect::<Vec<_>>()
                    .join(" | ")
            }
            Pattern::Tuple(pats, _) => {
                let inner = pats.iter()
                    .map(|p| self.emit_pattern_str(p))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("({})", inner)
            }
            _ => "_".into(),
        }
    }

    fn emit_enum_pattern_str(&self, e: &EnumPattern) -> String {
        if e.fields.is_empty() {
            return e.name.name.clone();
        }
        let fields = e.fields.iter().map(|f| match f {
            PatternField::Named(name, pat) =>
                format!("{}: {}", name.name, self.emit_pattern_str(pat)),
            PatternField::Positional(pat)  =>
                self.emit_pattern_str(pat),
            PatternField::Rest(_) => "..".into(),
        }).collect::<Vec<_>>().join(", ");
        format!("{} {{ {} }}", e.name.name, fields)
    }

    // ── Expression → Rust expression string ──────────────────

    pub fn emit_expr_str(&self, expr: &Expr) -> String {
        match expr {
            Expr::Lit(lit)         => self.emit_literal_str(lit),
            Expr::Ident(id)        => id.name.clone(),

            Expr::BinOp(b) => {
                let l = self.emit_expr_str(&b.lhs);
                let r = self.emit_expr_str(&b.rhs);
                let op = self.emit_binop_str(&b.op);
                format!("{} {} {}", l, op, r)
            }

            Expr::UnaryOp(u) => {
                let e = self.emit_expr_str(&u.expr);
                match u.op {
                    axon_parser::ast::UnaryOp::Neg => format!("-{}", e),
                    axon_parser::ast::UnaryOp::Not => format!("!{}", e),
                    _ => format!("/* unary */{}", e),
                }
            }

            Expr::Call(c) => {
                let args = c.args.iter()
                    .map(|a| self.emit_expr_str(&a.value))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({})", c.callee.name, args)
            }

            Expr::MethodCall(m) => {
                let recv = self.emit_expr_str(&m.receiver);
                let is_enum_constructor =
                    recv.chars().next().map(|c| c.is_uppercase()).unwrap_or(false)
                    && m.method.name.chars().next().map(|c| c.is_uppercase()).unwrap_or(false);

                if is_enum_constructor {
                    // ThreatLevel.Advisory(detail: x) → ThreatLevel::Advisory { detail: x }
                    let fields = m.args.iter()
                        .map(|a| {
                            let val = self.emit_expr_str(&a.value);
                            if let Some(label) = &a.label {
                                format!("{}: {}", label.name, val)
                            } else {
                                val
                            }
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    if fields.is_empty() {
                        format!("{}::{}", recv, m.method.name)
                    } else {
                        format!("{}::{}{{ {} }}", recv, m.method.name, fields)
                    }
                } else {
                    let args = m.args.iter()
                        .map(|a| self.emit_expr_str(&a.value))
                        .collect::<Vec<_>>()
                        .join(", ");
                    format!("{}.{}({})", recv, m.method.name, args)
                }
            }

            Expr::FieldAccess(f) => {
                let obj = self.emit_expr_str(&f.object);
                // Detect enum path: Capitalized.Capitalized → :: separator
                let is_enum_path = obj.chars().next()
                    .map(|c| c.is_uppercase())
                    .unwrap_or(false)
                    && f.field.name.chars().next()
                        .map(|c| c.is_uppercase())
                        .unwrap_or(false);
                if is_enum_path {
                    format!("{}::{}", obj, f.field.name)
                } else {
                    format!("{}.{}", obj, f.field.name)
                }
            }

            Expr::Index(i) => {
                let obj = self.emit_expr_str(&i.object);
                let idx = self.emit_expr_str(&i.index);
                format!("{}[{}]", obj, idx)
            }

            Expr::Propagate(inner, _) => {
                let e = self.emit_expr_str(inner);
                format!("{}?", e)
            }

            Expr::List(l) => {
                let items = l.elements.iter()
                    .map(|e| self.emit_expr_str(e))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("vec![{}]", items)
            }

            Expr::Return(val, _) => {
                match val.as_ref() {
                    Some(e) => format!("return {}", self.emit_expr_str(e)),
                    None    => "return".into(),
                }
            }

            Expr::Break_(val, _) => {
                match val.as_ref() {
                    Some(e) => format!("break {}", self.emit_expr_str(e)),
                    None    => "break".into(),
                }
            }

            _ => "/* expr */".into(),
        }
    }

    fn emit_literal_str(&self, lit: &Literal) -> String {
        match lit {
            Literal::Int(n, _)   => n.to_string(),
            Literal::Float(f, _) => format!("{}", f),
            Literal::Str(s, _)   => format!("\"{}\"", s),
            Literal::Bool(b, _)  => b.to_string(),
            Literal::None(_)     => "None".into(),
            Literal::Bytes(_, _) => "vec![]".into(),
        }
    }

    fn emit_binop_str(&self, op: &axon_parser::ast::BinOp) -> &'static str {
        use axon_parser::ast::BinOp;
        match op {
            BinOp::Add    => "+",  BinOp::Sub    => "-",
            BinOp::Mul    => "*",  BinOp::Div    => "/",
            BinOp::Mod    => "%",
            BinOp::Eq     => "==", BinOp::NotEq  => "!=",
            BinOp::Lt     => "<",  BinOp::Gt     => ">",
            BinOp::LtEq   => "<=", BinOp::GtEq   => ">=",
            BinOp::And    => "&&", BinOp::Or     => "||",
            BinOp::BitAnd => "&",  BinOp::BitOr  => "|",
            BinOp::BitXor => "^",  BinOp::Shl    => "<<",
            BinOp::Shr    => ">>",
            _ => "/* op */",
        }
    }
}
