pub mod dwc;
// ============================================================
// AXON Codegen — lib.rs
// AXON → Rust Transpiler — Phase 3
// Copyright © 2026 Edison Lepiten — AIEONYX
// github.com/aieonyx/axon
//
// Entry point:
//   codegen(source) → Result<String, CodegenError>
//
// Pipeline:
//   AXON source
//     ↓ lex + inject_indentation
//   Token stream
//     ↓ parse
//   AST (Program)
//     ↓ codegen
//   Rust source (String)
//     ↓ (caller invokes rustc / cargo)
//   Native binary
// ============================================================

pub mod generator;
pub mod types;
pub mod error;

pub use generator::CodeGen;
pub use apr::APR;
pub mod apr;
pub use error::CodegenError;

use axon_lexer::FileId;

/// Transpile AXON source to Rust source.
/// Returns the complete Rust source as a String.
pub fn codegen(source: &str) -> Result<String, CodegenError> {
    let file_id = FileId(1);

    // Step 1: Parse
    let result = axon_parser::parse(source, file_id);
    if !result.errors.is_empty() {
        return Err(CodegenError::ParseErrors(
            result.errors.iter()
                .map(|e| format!("{:?}", e))
                .collect()
        ));
    }

    // Step 2: Generate Rust
    let mut gen = CodeGen::new();
    gen.emit_program(&result.program);
    Ok(gen.finish())
}

/// Transpile AXON source to Rust — returns errors as a
/// formatted diagnostic string instead of aborting.
pub fn codegen_with_diagnostics(source: &str) -> CodegenResult {
    let file_id = FileId(1);
    let result  = axon_parser::parse(source, file_id);

    let parse_errors: Vec<String> = result.errors.iter()
        .map(|e| format!("{:?}", e))
        .collect();

    let rust_source = if parse_errors.is_empty() {
        let mut gen = CodeGen::new();
        gen.emit_program(&result.program);
        Some(gen.finish())
    } else { None };

    CodegenResult { rust_source, parse_errors }
}

pub struct CodegenResult {
    pub rust_source  : Option<String>,
    pub parse_errors : Vec<String>,
}

impl CodegenResult {
    pub fn is_ok(&self) -> bool { self.parse_errors.is_empty() }
}

// ── Tests ─────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_codegen_empty_module() {
        let src = "module hello\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("// module hello"));
        assert!(result.contains("Generated by AXON Transpiler"));
    }

    #[test]
    fn test_codegen_struct() {
        let src = "struct Config:\n    host : Str\n    port : Int\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub struct Config"));
        assert!(result.contains("pub host : String"));
        assert!(result.contains("pub port : i64"));
    }

    #[test]
    fn test_codegen_enum_unit_variants() {
        let src = "enum Status:\n    Active\n    Inactive\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub enum Status"));
        assert!(result.contains("Active,"));
        assert!(result.contains("Inactive,"));
    }

    #[test]
    fn test_codegen_enum_data_variants() {
        let src = concat!(
            "enum ThreatLevel:\n",
            "    Clear\n",
            "    Advisory(detail: Str)\n",
            "    Critical(layer: Int, detail: Str)\n",
        );
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub enum ThreatLevel"));
        assert!(result.contains("Clear,"));
        assert!(result.contains("Advisory {"));
        assert!(result.contains("detail : String,"));
        assert!(result.contains("Critical {"));
        assert!(result.contains("layer : i64,"));
    }

    #[test]
    fn test_codegen_fn_basic() {
        let src = "fn hello():\n    pass\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub fn hello()"));
    }

    #[test]
    fn test_codegen_fn_with_params_and_return() {
        let src = "fn add(x : Int, y : Int) -> Int:\n    return x\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub fn add(x: i64, y: i64) -> i64"));
        assert!(result.contains("return x;"));
    }

    #[test]
    fn test_codegen_task_async() {
        let src = "task monitor() -> Int:\n    pass\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("pub async fn monitor()"));
    }

    #[test]
    fn test_codegen_let_stmt() {
        let src = "fn f():\n    let x = 42\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("let x = 42;"));
    }

    #[test]
    fn test_codegen_return_stmt() {
        let src = "fn f() -> Int:\n    return 99\n";
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("return 99;"));
    }

    #[test]
    fn test_codegen_aegis_monitor() {
        let src = concat!(
            "module aieonyx.aegis.monitor\n",
            "import axon.sys.sel4.ipc as ipc\n",
            "enum ThreatLevel:\n",
            "    Clear\n",
            "    Advisory(detail: Str)\n",
            "fn classify(signal : Int) -> ThreatLevel:\n",
            "    return ThreatLevel.Clear\n",
        );
        let result = codegen(src).expect("codegen failed");
        assert!(result.contains("// module aieonyx.aegis.monitor"));
        assert!(result.contains("pub enum ThreatLevel"));
        assert!(result.contains("pub fn classify(signal: i64)"));
    }

    #[test]
    fn test_codegen_parse_error_propagated() {
        // Malformed source should produce CodegenError::ParseErrors
        let src = "struct :\n"; // missing name
        let result = codegen(src);
        assert!(result.is_err());
        matches!(result.unwrap_err(), CodegenError::ParseErrors(_));
    }
}

/// Parallel codegen — compiles fn items using rayon.
/// Enable with AXON_PARALLEL=1 environment variable.
pub fn codegen_parallel(source: &str) -> Result<String, CodegenError> {
    use rayon::prelude::*;
    use axon_parser::ast::TopLevelItem;

    let file_id = FileId(1);
    let result  = axon_parser::parse(source, file_id);
    if !result.errors.is_empty() {
        return Err(CodegenError::ParseErrors(
            result.errors.iter().map(|e| format!("{:?}", e)).collect()
        ));
    }
    let program = &result.program;

    // Step 1: Build enum registry once (sequential — needed for type resolution)
    let mut base_gen = CodeGen::new();
    base_gen.build_enum_registry(program);
    let registry = base_gen.enum_registry.clone();

    // Step 2: Emit header + imports + non-fn items sequentially
    let mut header_gen = CodeGen::new();
    header_gen.build_enum_registry(program);
    header_gen.emit_program_header(program);
    for item in &program.items {
        match item {
            TopLevelItem::Fn(_) | TopLevelItem::Task(_) => {}
            other => { header_gen.emit_top_level_item(other); header_gen.blank(); }
        }
    }
    let header_output = header_gen.finish();

    // Step 3: Compile fn/task items in parallel
    let fn_items: Vec<(usize, &TopLevelItem)> = program.items
        .iter()
        .enumerate()
        .filter(|(_, i)| matches!(i, TopLevelItem::Fn(_) | TopLevelItem::Task(_)))
        .collect();

    let mut fn_outputs: Vec<(usize, String)> = fn_items
        .par_iter()
        .map(|(idx, item)| {
            let mut gen = CodeGen::new();
            gen.enum_registry = registry.clone();
            gen.emit_top_level_item(item);
            gen.blank();
            (*idx, gen.finish())
        })
        .collect();

    fn_outputs.sort_by_key(|(idx, _)| *idx);

    let fn_output: String = fn_outputs.into_iter().map(|(_, s)| s).collect();
    Ok(header_output + &fn_output)
}

