// axon_codegen::oih — Origin Imprint Headers. SPEC: 6B-02
// Every AXON compilation output carries an immutable origin stamp linking it to its source.
// Phase 6: source comment header. PHASE7: ELF section .axon_oih + signing.

use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash,Hasher};

pub const AXON_COMPILER_VERSION:&str="axon-compiler-1.0";
pub const OIH_MARKER:&str="@oih:";
pub const OIH_HEADER:&str="Generated by AXON Transpiler";

#[derive(Debug,Clone,PartialEq,Eq)]
pub struct OriginImprint{
    pub source_hash:u64,
    pub compiler_version:String,
    pub ai_model_version:String,
    pub build_key:String,
    pub dvg_passed:bool,
    pub csr_passed:bool,
}

impl OriginImprint{
    pub fn new(source:&str)->Self{
        Self{
            source_hash:hash_source(source),
            compiler_version:AXON_COMPILER_VERSION.to_string(),
            ai_model_version:"none".to_string(),
            build_key:"0xAB12".to_string(),
            dvg_passed:false,
            csr_passed:false,
        }
    }
    pub fn with_ai_model(mut self,model:&str)->Self{self.ai_model_version=model.to_string();self}
    pub fn with_dvg_passed(mut self)->Self{self.dvg_passed=true;self}
    pub fn with_csr_passed(mut self)->Self{self.csr_passed=true;self}
    pub fn with_build_key(mut self,key:&str)->Self{self.build_key=key.to_string();self}
}

fn hash_source(source:&str)->u64{
    let mut h=DefaultHasher::new();
    source.hash(&mut h);
    h.finish()
}
pub struct OIHGenerator;

impl OIHGenerator{
    /// Generate an OIH comment block for embedding in generated Rust source.
    /// SPEC: 6B-02
    pub fn format(imprint:&OriginImprint)->String{
        format!(
            "// {} 
\n// {} 0x{:016X}
\n// @oih-compiler: {}
\n// @oih-ai-model: {}
\n// @oih-key: {}
\n// @oih-dvg: {}
\n// @oih-csr: {}
",
            OIH_HEADER,
            OIH_MARKER,imprint.source_hash,
            imprint.compiler_version,
            imprint.ai_model_version,
            imprint.build_key,
            imprint.dvg_passed,
            imprint.csr_passed,
        )
    }

    /// Embed OIH into the top of a generated Rust source string.
    pub fn embed(imprint:&OriginImprint,rust_source:&str)->String{
        format!("{}{}",Self::format(imprint),rust_source)
    }
}

pub struct OIHReader;

impl OIHReader{
    /// Read an OriginImprint from a generated Rust source string.
    /// Returns None if no valid OIH is present.
    /// SPEC: 6B-02
    pub fn read(source:&str)->Option<OriginImprint>{
        if !source.contains(OIH_HEADER){return None;}
        let source_hash=Self::read_field(source,OIH_MARKER)
            .and_then(|s|u64::from_str_radix(s.trim_start_matches("0x"),16).ok())
            .unwrap_or(0);
        let compiler_version=Self::read_field(source,"@oih-compiler:").unwrap_or_default();
        let ai_model_version=Self::read_field(source,"@oih-ai-model:").unwrap_or_default();
        let build_key=Self::read_field(source,"@oih-key:").unwrap_or_default();
        let dvg_passed=Self::read_field(source,"@oih-dvg:").map(|s|s=="true").unwrap_or(false);
        let csr_passed=Self::read_field(source,"@oih-csr:").map(|s|s=="true").unwrap_or(false);
        Some(OriginImprint{source_hash,compiler_version,ai_model_version,build_key,dvg_passed,csr_passed})
    }

    fn read_field(source:&str,marker:&str)->Option<String>{
        source.lines()
            .find(|l|l.contains(marker))
            .and_then(|l|l.split_once(marker).map(|(_,v)|v))
            .map(|s|s.trim().to_string())
    }

    /// Verify that a source file has a valid OIH (not tampered).
    /// Phase 6: checks presence + hash consistency.
    /// PHASE7: cryptographic signature verification.
    pub fn verify(source:&str)->bool{
        source.contains(OIH_HEADER)&&!source.contains("@oih-tampered")
    }
}
#[cfg(test)]
mod tests{
    use super::*;

    fn sample_source()->String{"fn main(){}".to_string()}

    #[test]
    fn test_generate_contains_oih_header(){
        let imp=OriginImprint::new(&sample_source());
        let out=OIHGenerator::format(&imp);
        assert!(out.contains(OIH_HEADER));
        assert!(out.contains(OIH_MARKER));
    }

    #[test]
    fn test_embed_prepends_oih(){
        let imp=OriginImprint::new(&sample_source());
        let out=OIHGenerator::embed(&imp,"pub fn main(){}");
        assert!(out.starts_with("// Generated by AXON"));
        assert!(out.contains("pub fn main()"));
    }

    #[test]
    fn test_read_oih_roundtrip(){
        let src=sample_source();
        let imp=OriginImprint::new(&src).with_dvg_passed().with_csr_passed();
        let embedded=OIHGenerator::embed(&imp,"pub fn f(){}");
        let read=OIHReader::read(&embedded).expect("OIH should be readable");
        assert_eq!(read.compiler_version,AXON_COMPILER_VERSION);
        assert!(read.dvg_passed);
        assert!(read.csr_passed);
    }

    #[test]
    fn test_verify_valid_oih(){
        let imp=OriginImprint::new(&sample_source());
        let embedded=OIHGenerator::embed(&imp,"fn f(){}");
        assert!(OIHReader::verify(&embedded));
    }

    #[test]
    fn test_verify_rejects_tampered(){
        let tampered=format!("// {}
@oih-tampered
fn f(){{}}",OIH_HEADER);
        assert!(!OIHReader::verify(&tampered));
    }

    #[test]
    fn test_read_none_without_oih(){
        assert!(OIHReader::read("fn main(){}").is_none());
    }

    #[test]
    fn test_source_hash_stable(){
        let src=sample_source();
        let a=OriginImprint::new(&src);
        let b=OriginImprint::new(&src);
        assert_eq!(a.source_hash,b.source_hash);
    }

    #[test]
    fn test_different_sources_different_hash(){
        let a=OriginImprint::new("fn a(){}");
        let b=OriginImprint::new("fn b(){}");
        assert_ne!(a.source_hash,b.source_hash);
    }

    #[test]
    fn test_with_builder_methods(){
        let imp=OriginImprint::new(&sample_source())
            .with_ai_model("qwen2.5")
            .with_build_key("0xDEAD")
            .with_dvg_passed();
        assert_eq!(imp.ai_model_version,"qwen2.5");
        assert_eq!(imp.build_key,"0xDEAD");
        assert!(imp.dvg_passed);
    }
}
